"""Add restaurant_id to dishes

Revision ID: a407227db69d
Revises: 4aeac4f5bb3d
Create Date: 2025-03-11 22:58:22.880253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a407227db69d'
down_revision: Union[str, None] = '4aeac4f5bb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'restaurant_id')
    # ### end Alembic commands ###
